import { type Dictionary, t } from "intlayer";
import type { Metadata } from "next";

const metadataContent = {
  key: "page-metadata",
  content: {
    title: t({
      en: "Create Next App",
      ja: "日本語：Create Next App",
    }),
    description: t({
      en: "Generated by create next app",
      ja: "日本語：Generated by create next app",
    }),
  },
} satisfies Dictionary<Metadata>;

export default metadataContent;
